name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    # Include asciidoctor-action and run the cli tool
    - uses: mgred/asciidoctor-action@master
      with:
        args: asciidoctor -b pdf ../../Doc/index.adoc
