name: CI

on: [push]

jobs:
  build:
    runs-on: [windows-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Build DotNET35
        run: |
           cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
           .\MSBuild.exe /restore $Env:GITHUB_WORKSPACE\XPlaneLauncher.sln 
